= クイズゲーム: 定数一覧
:lang: ja
:doctype: book
:toc: left
:toclevels: 5
:toc-title: 目次
:sectnums:
:sectnumlevels: 5
:sectlinks:
:imagesdir: ./images
:icons: font
:source-highlighter: coderay
:example-caption: 例
:table-caption: 表
:figure-caption: 図

[#変更履歴, title="変更履歴", cols="1,2,3,3,3,3,3", options="header", align="center"]
|===
^.^|No. ^.^|版数 ^.^|変更者 <.^|作成日/変更日 <.^|仕変番号/障害番号 <.^|変更箇所 <.^|変更内容

^.^|{counter:変更履歴} |1.00 |Takumi Harada |2026-04-04 ^.^|- ^.^|- |新規作成
|===

== 定数一覧

[#定数一覧, title="定数一覧", cols="1,5,3,4,5", options="header", align="center"]
|===
^.^|No. ^.^|定数名 ^.^|型 ^.^|設定値 ^.^|備考

^.^|{counter:定数} <.^|GameConstants.QUESTION_COUNT <.^|number <.^|10 <.^|1 ゲームで出題する問題数
^.^|{counter:定数} <.^|GameConstants.STANDARD_DELAY <.^|number <.^|1800 <.^|通常モード正誤判定待機時間 (ms)
^.^|{counter:定数} <.^|GameConstants.CORRECT_DELAY <.^|number <.^|1200 <.^|正解後の次問題遷移待機時間 (ms)
^.^|{counter:定数} <.^|GameConstants.LOSE_DELAY <.^|number <.^|800 <.^|不正解後ゲームオーバー遷移待機時間 (ms)
^.^|{counter:定数} <.^|GameConstants.CPA_DELAY <.^|number <.^|2500 <.^|CPA モード正誤判定待機時間 (ms)
^.^|{counter:定数} <.^|GameConstants.CPA_LOSE_DELAY <.^|number <.^|1000 <.^|CPA モード不正解後遷移待機時間 (ms)
^.^|{counter:定数} <.^|GameConstants.SECRET_CLICKS <.^|number <.^|6 <.^|CPA 解放に必要なタイトルロゴクリック数
^.^|{counter:定数} <.^|GameConstants.RUMBLE_THRESHOLD <.^|number <.^|4 <.^|振動エフェクト開始クリック数
^.^|{counter:定数} <.^|GameConstants.RESET_TIMEOUT <.^|number <.^|1200 <.^|クリック累積リセットまでの待機時間 (ms)
^.^|{counter:定数} <.^|GameConstants.UNLOCK_DELAY <.^|number <.^|200 <.^|解放ダイアログ表示遅延 (ms)
^.^|{counter:定数} <.^|GameConstants.STANDARD_REWARDS <.^|number[] <.^|[10000, 20000, 30000, 50000, 100000, 150000, 250000, 500000, 750000, 1000000] <.^|通常モード賞金テーブル（問題1〜10）
^.^|{counter:定数} <.^|GameConstants.CPA_REWARDS <.^|number[] <.^|[10000, 100000, 500000, 1000000, 2000000, 4000000, 6000000, 8000000, 9000000, 10000000] <.^|CPA モード賞金テーブル（問題1〜10）
|===
